### ISSUE TITLE
Propose a proposal?

### ISSUE THREAD

**Issue by alexellis** [teamserverless/proposals#1]
Would you like to propose a proposal by opening your own issue?

Comment below with a single emoji to let us know what you feel.

When you're done, view the result here:

http://206.189.126.36/function/view

[View the code](https://github.com/alexellis/comment-vibes)

**Comment by alexellis** [comment]
👍

**Comment by alexellis** [comment]
👍

**Comment by alexellis** [comment]
👀

**Comment by alexellis** [comment]
🏷

**Comment by alexellis** [comment]
Invalid

**Comment by rberrelleza** [comment]
🥇

**Comment by rberrelleza** [comment]
👍

**Comment by rberrelleza** [comment]
🥇

**Comment by aidun** [comment]
:1st_place_medal:

**Comment by blaisep** [comment]
👀  (the emoji has to be in a new comment in order to increment the counter)

**Comment by burtonr** [comment]
💯

**Comment by burtonr** [comment]
🥇

**Comment by blaisep** [comment]
💰 Is this Chicago? Can we vote multiple times?

**Comment by burtonr** [comment]
> 
> 
> 💰 Is this Chicago? Can we vote multiple times?

Doesn't appear to work with text alongside the vote/emoji

**Comment by alexellis** [comment]
Correct. Trimming was too hard for the time constraints.

**Comment by alexellis** [comment]
Also, there's no GitHub API for reactions, which is why we have to send comments

**Comment by alexellis** [comment]
🍒

**Comment by alexellis** [comment]
My Raspberry Pi 4 cluster just handled that event! ☝️

**Comment by alexellis** [comment]
🍌

**Comment by alexellis** [comment]
🍒

**Comment by k33g** [comment]
🎃

**Comment by k33g** [comment]
🐼 🐯

**Comment by alexellis** [comment]
One at a time :)

**Comment by alexellis** [comment]
Oh, or maybe not!

**Comment by alexellis** [comment]
🐼 🐯

**Comment by alexellis** [comment]
🐼

**Comment by alexellis** [comment]
🐯

**Comment by grampelberg** [comment]
🌭

**Comment by eddiezane** [comment]
:sunrise_over_mountains:

**Comment by JensWallat** [comment]
;-)

**Comment by trifygri** [comment]
😷
